# Generated by Django 6.0.3 on 2026-03-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maids', '0001_initial'),
    ]

    def create_dummies(apps, schema_editor):
        Maid = apps.get_model('maids', 'Maid')
        maids_data = [
            {'name': 'Asha', 'skills': 'Cleaning, Cooking', 'experience': 3, 'location': 'Bangalore', 'availability': True, 'avg_rating': 4.5},
            {'name': 'Lakshmi', 'skills': 'Babysitting, Cooking', 'experience': 5, 'location': 'Mysore', 'availability': True, 'avg_rating': 4.7},
            {'name': 'Priya', 'skills': 'Cleaning, Ironing', 'experience': 2, 'location': 'Bangalore', 'availability': True, 'avg_rating': 4.2},
            {'name': 'Sunita', 'skills': 'Cooking, Babysitting', 'experience': 4, 'location': 'Mysore', 'availability': False, 'avg_rating': 4.8},
            {'name': 'Rani', 'skills': 'Cleaning', 'experience': 6, 'location': 'Bangalore', 'availability': True, 'avg_rating': 4.6},
            {'name': 'Geeta', 'skills': 'Cooking, Ironing', 'experience': 1, 'location': 'Mysore', 'availability': True, 'avg_rating': 4.0},
            {'name': 'Kavita', 'skills': 'Babysitting', 'experience': 7, 'location': 'Bangalore', 'availability': True, 'avg_rating': 4.9},
            {'name': 'Meera', 'skills': 'Cleaning, Cooking, Babysitting', 'experience': 3, 'location': 'Mysore', 'availability': True, 'avg_rating': 4.4},
        ]
        for data in maids_data:
            Maid.objects.get_or_create(**data)

    operations = [
        migrations.RunPython(create_dummies),
    ]
