# Generated by Django 6.0.3 on 2026-03-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maids', '0002_auto_20260324_2047'),
    ]

    operations = [
    ]
