# Generated by Django 6.0.3 on 2026-03-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maids', '0004_maid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='maid',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='maid',
            name='photo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
