# Generated by Django 6.0.3 on 2026-03-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maids', '0005_maid_phone_alter_maid_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='maid',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
