# Generated by Django 6.0.3 on 2026-03-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
